# Generated by Django 5.1.1 on 2024-09-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='country_archive',
            field=models.BooleanField(default=False),
        ),
    ]
