# Generated by Django 5.1.1 on 2024-09-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_city_city_archive_country_country_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='country',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2),
        ),
    ]
